Changed default behavior to not auto resolve deps Added remove or url in package.xml file if not git repository is specified updated mrt init script Changed scripts to that they can be executed everywere in the workspace Improved output of mrt_resolve_deps if a package is not found and also fixed infinite loop bug Improved mrt_setup_gitlab script Improved test.cpp

diff --git a/scripts/mrt_clone_package b/scripts/mrt_clone_package
--- a/scripts/mrt_clone_package
+++ b/scripts/mrt_clone_package
@@ -9,6 +9,27 @@ if [ -z "$ROS_ROOT" ]; then
 	exit 1
 fi
 
+#search for catkin root workspace dir
+function get_workspace_root_folder {
+	x=$1; 
+	while [[ "$x" != "/" ]]; do 		
+		p=$(find "$x" -maxdepth 1 -type d -name ".catkin_tools")
+        if [[ $p != "" ]]; then
+			echo "$p"
+			return
+		fi
+		x=`dirname "$x"`
+	done
+}
+
+WORKSPACE_ROOT_FOLDER=$(get_workspace_root_folder $PWD)
+if [[ "$WORKSPACE_ROOT_FOLDER" == "" ]]; then
+	echo "Cannot find workspace root folder."
+	exit 1
+fi
+
+cd "$WORKSPACE_ROOT_FOLDER"
+
 if ! [ -d "src" ]; then
     echo "No source folder found. This must be run in a standard catkin workspace (where you ran catkin_make)"
     exit 1
@@ -35,7 +56,6 @@ if ! [ -z "$GIT_ERROR" ]; then
 fi
 
 #checkout repository
-
 wstool set $PACKAGE_NAME --git $GIT_REPOSITORY --confirm -t ./src 2>/dev/null > /dev/null
 echo "$(tput setaf 1)Search for package $PACKAGE_NAME $(tput sgr0)"
 echo "$(tput setaf 2)Found in $GIT_REPOSITORY. Cloning.$(tput sgr0)"
diff --git a/scripts/mrt_create_pkg b/scripts/mrt_create_pkg
--- a/scripts/mrt_create_pkg
+++ b/scripts/mrt_create_pkg
@@ -88,7 +88,7 @@ func_create_files() {
 		cp $SELF_DIR/templates/package.xml package.xml
 	fi
 	
-	sed -i -e "s/\${PACKAGE_NAME}/$PKG_NAME/g" -e "s/\${CMAKE_PACKAGE_NAME}/${PKG_NAME^^}/g" -e "s/\${USER_NAME}/$USR_NAME/g" -e "s/\${USER_EMAIL}/$USR_EMAIL/g" package.xml
+	sed -i -e "s/\${PACKAGE_NAME}/$PKG_NAME/g" -e "s/\${CMAKE_PACKAGE_NAME}/${PKG_NAME^^}/g" -e "s/\${USER_NAME}/$USR_NAME/g" -e "s/\${USER_EMAIL}/$USR_EMAIL/g" -e "/  <url/d" package.xml
 	
 	# CMakeLists.txt
 	#build mask @12|345@
@@ -174,8 +174,29 @@ where:
 func_exit
 }
 
+function get_workspace_root_folder {
+	x=$1; 
+	while [[ "$x" != "/" ]]; do 		
+		p=$(find "$x" -maxdepth 1 -type d -name ".catkin_tools")
+        if [[ $p != "" ]]; then
+			echo "$p"
+			return
+		fi
+		x=`dirname "$x"`
+	done
+}
+
 ##################################### KONFIG LADEN ######################################
 # Handle option flags
+
+WORKSPACE_ROOT_FOLDER=$(get_workspace_root_folder $PWD)
+if [[ "$WORKSPACE_ROOT_FOLDER" == "" ]]; then
+	echo "Cannot find workspace root folder."
+	exit 1
+fi
+
+cd "$WORKSPACE_ROOT_FOLDER"
+
 OPTIND=1
 while getopts "ht:rg" opt; do # set $opt to the next passed option
   case $opt in
diff --git a/scripts/mrt_wstool_update b/scripts/mrt_wstool_update
--- a/scripts/mrt_wstool_update
+++ b/scripts/mrt_wstool_update
@@ -1,5 +1,26 @@
 #!/bin/bash
 
+#search for catkin root workspace dir and change folder
+function get_workspace_root_folder {
+	x=$1; 
+	while [[ "$x" != "/" ]]; do 		
+		p=$(find "$x" -maxdepth 1 -type d -name ".catkin_tools")
+        if [[ $p != "" ]]; then
+			echo "$p"
+			return
+		fi
+		x=`dirname "$x"`
+	done
+}
+
+WORKSPACE_ROOT_FOLDER=$(get_workspace_root_folder $PWD)
+if [[ "$WORKSPACE_ROOT_FOLDER" == "" ]]; then
+	echo "Cannot find workspace root folder."
+	exit 1
+fi
+
+cd "$WORKSPACE_ROOT_FOLDER"
+
 if [ ! -d "src" ]; then
     echo "No source folder found. This must be run in a standard catkin workspace (where you ran catkin_make)"
     exit 1
@@ -9,6 +30,7 @@ if [[ -f "src/.rosinstall" && "$#" -gt "0" && "$1" == "init" ]]; then
    echo "$(tput setaf 4)Removing wstool database src/.rosinstall$(tput sgr0)"
    rm -f src/.rosinstall
 fi 
+
 if [ ! -f "src/.rosinstall" ]; then 
     echo "Initializing wstool in ./src"
     wstool init ./src > /dev/null
